version: '3'

services:
  gcp-navi-db:
      image: postgres:latest
      restart: always
      container_name: gcp-navi-db
      environment:
        POSTGRES_USER: 'postgres' 
        POSTGRES_PASSWORD: 'postgres' 
      volumes:
        - ./init_db:/docker-entrypoint-initdb.d
      ports:
        - "0.0.0.0:5432:5432"